version: '3.8'

services:
  db:
    image: mysql:8
    container_name: vaazar-mysql
    restart: always
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: usersdb_user
      MYSQL_PASSWORD: _usersdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: vaazar-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: vaazar-redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-_redispw}"]
    ports:
      - "6379:6379"

volumes:
  mysql_data:
