spring.datasource.url = jdbc:mysql://localhost:3306/users_db?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=usersdb_user
spring.datasource.password=_usersdb
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springdoc.swagger-ui.path=/documentation

spring.jackson.visibility.field=any
spring.jackson.visibility.getter=none
spring.jackson.visibility.is-getter=none
spring.jackson.visibility.setter=none

app.paths.firebase-keys=c:/app/firebase.json
aws.credentials.bucketUserAccessId=AKIA3C2C6PY6OACPEPV3
aws.credentials.bucketUserSecretKey=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
aws.region.preferred=eu-central-1
aws.s3.userProfilesBucket=vuspr
aws.s3.userDocumentsBucket=vusdo